### ISSUE TITLE
How to group Validate result by row number

### ISSUE THREAD

**Issue by samagit** [zorgoz/EPPlus.TableAsEnumerable#2]
Hi Zorgoz,

The validate method works fine, but I need to group the resulting errors by row number. because the end user needs to list them by row number.
`var errors = table.Validate<myDto>().ToList();`
Thanks
Samad

**Comment by zorgoz** [comment]
Hello. As a table is rather a named region of a worksheet that resembles the relational table concept, thus it is a set of rows (thus theoretically unordered). Anywas the `ExcelTableConvertExceptionArgs` has a `cellAddress` property of type `ExcelCellAddress` ([see source](https://github.com/pruiz/EPPlus/blob/master/EPPlus/ExcelCellAddress.cs)), that is filled during validation. You could have something like this:

`var errors = table.Validate<myDto>().GroupBy(x => x.cellAddress.Row);`

**Comment by zorgoz** [comment]
Please let me know whether my answer helped you!

**Comment by samagit** [comment]
Yes it was helpful. Here is my final solution:

```
                    var errors = table.Validate<MyDto>().GroupBy(x => x.cellAddress.Row).ToList();
                    if(errors.Count>0)
                    {
                        foreach (var errorGrp in errors)
                        {
                            var rowErrors = new List<string>();
                            
                            foreach (var item in errorGrp)
                            {
                                rowErrors.Add(string.Format("[{0}], {1}, Value: {2}, expected: {3}", item.columnName, item.propertyName, item.cellValue,  item.expectedType));
                            }

                            errorList.Add(errorGrp.Key, rowErrors);
                        }
                    }
```

I found though that the returned error is not human readable enough and needs to be simplified.
Thanks
